name: final
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - python-dotenv
  - pip:
      - lightgbm==4.6.0
      - shap==0.49.1
      - fastapi
      - uvicorn[standard]
